"""add users

Revision ID: ce3a01b790d1
Revises: 3b4e8b9ed622
Create Date: 2026-07-28 16:04:27.103675

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import orm
import bcrypt


from src.models.user import User

# revision identifiers, used by Alembic.
revision: str = "ce3a01b790d1"
down_revision: Union[str, Sequence[str], None] = "3b4e8b9ed622"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_hash_password(password: str) -> bytes:
    """
    Создание хеш пароля
    :param password: пароль
    :type password: str
    :rtype: bytes
    :return: хеш значение пароля
    """
    salt = bcrypt.gensalt()
    pwd_bytes: bytes = password.encode()
    return bcrypt.hashpw(pwd_bytes, salt)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    password_for_user: str = create_hash_password("1qaz!QAZ").decode()
    user: User = User(
        name="revisor",
        hashed_password=password_for_user,
        is_superuser=True,
        is_active=True,
    )
    session.add(user)
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
